config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :players, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :teams, only: [] do
    collection do
      get :search
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_season

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def set_season
    @season = Season.find_by(year: '2022')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_filters.html.erb
<div class='my-4 row filters' data-controller='filter' data-filter-player-id-value="<%= @player.id %>">
  <div class="col-12 col-sm-4 my-1 my-sm-0">
    <div class="input-group filter-label">
      <span class="input-group-text">Age</span>
      <input type="number" min="16" max="60" aria-label="First name" class="form-control" name='age_min' placeholder='min' data-filter-target='age_min' data-action='keyup->filter#update' autocomplete='off'>
      <input type="number" min="17" max="60" aria-label="Last name" class="form-control" name='age_max' placeholder='max' data-filter-target='age_max' data-action='keyup->filter#update' autocomplete='off'>
    </div>
  </div>
  <div class="col-12 col-sm-5 my-1 my-sm-0">
    <div class="input-group filter-label">
      <span class="input-group-text">€</span>
      <input type="number" min="1" max="" step="1"aria-label="First name" class="form-control" name='value_min' placeholder='min' data-filter-target='value_min' data-action='keyup->filter#update' autocomplete='off'>
      <input type="number" min="1" max="" step="1"aria-label="Last name" class="form-control" name='value_max' placeholder='max' data-filter-target='value_max' data-action='keyup->filter#update' autocomplete='off'>
      <span class="input-group-text">million</span>
    </div>
  </div>
  <div class="col-12 col-sm-3 my-1 my-sm-0">
    <% if false %>
      <select name="states" data-controller="select2" data-select2-options-values='{ "tags": true, "width": "resolve" }' multiple="multiple" class="w-100" data-filter-target='position'>>
        <option value="">All</option>
        <% @positions.each do |pos| %>
          <option value=""><%= pos %></option>
        <% end %>
      </select>
    <% end %>
    <select class="form-select small-font" aria-label="Default select example" data-filter-target='position' data-action='change->filter#update'>
      <option <%= 'selected' unless params[:position] %> value="All">All</option>
      <% @positions.each do |pos| %>
        <option value="<%= pos %>" <%= 'selected' if params[:position] == pos %>><%= pos %></option>
        <% end %>
      </select>
    </div>
  </div>
</div>

app/views/application/_header.html.erb
<div class="row justify-content-center">
  <div class="col">
    <div class="d-flex justify-content-between">
      <div>
        <h1 class="text-white d-flex align-items-center">
          <%= image_tag @team.club_flag_url, width: '40px', height: '40px', class: 'me-1' %>
          <%= @team.name %>
        </h1>
      </div>
      <% if false %>
        <div class="d-flex text-center">
          <div>
            <p>Liverpool F.C.</p>
            <small>Player Recruitment</small>
          </div>
          <%= image_tag 'https://logoeps.com/wp-content/uploads/2011/08/liverpool-logo-vector.png', width: '40px', height: '40px', class: 'ms-1' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/application/_positions.html.erb
<div class="btn-group">
  <%= link_to 'All', players_path(team_id: @team.id), class: "btn border-light #{'btn-secondary active' if params['position'].blank? }" %>
  <%= link_to 'FW', players_path(team_id: @team.id, position: 'FW'), class: "btn border-light #{'btn-secondary active' if params['position'] == 'FW'}" %>
  <%= link_to 'MF', players_path(team_id: @team.id, position: 'MF'), class: "btn border-light #{'btn-secondary active' if params['position'] == 'MF'}" %>
  <%= link_to 'DF', players_path(team_id: @team.id, position: 'DF'), class: "btn border-light #{'btn-secondary active' if params['position'] == 'DF'}" %>
  <%= link_to 'GK', players_path(team_id: @team.id, position: 'GK'), class: "btn border-light #{'btn-secondary active' if params['position'] == 'GK'}" %>
</div>

app/views/application/_tabs.html.erb
<div class="row mt-4">
  <div class="col">
    <ul class="list-inline tabs-underlined">
      <li>
        <%= link_to 'Squad', players_path(team_id: @team.id), class: "tab-underlined #{'active' if active == 'squads'}" %>
      </li>
      <li>
        <% if active == 'targets' %>
          <%= link_to 'Targets', '#', class: "tab-underlined #{'active' if active == 'targets'}" %>
        <% else %>
          <%= link_to 'Targets', player_path(@team.players&.first), class: "tab-underlined" %>
        <% end %>
      </li>
      <% if false %>
        <li>
          <%= link_to 'Search', '#', class: "tab-underlined #{'active' if active == 'search'}" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>